'use strict';

/**
 * QCT × Hyperliquid — Vault Manager
 *
 * Mirrors the QCT Prosperity Cascade on Hyperliquid's vault infrastructure.
 * Vault leader (you) earns 10% of all profits generated by the vault strategy.
 *
 * HOW IT WORKS:
 *   1. Users deposit USDC into an HL vault you create at app.hyperliquid.xyz
 *   2. The vault runs the ArbEngine strategy
 *   3. Profits split via Prosperity Cascade:
 *      L1 (40%) → vault depositors — distributed automatically by HL
 *      L2 (30%) → lock-tier stakers — tracked here, paid at 24h intervals
 *      L3 (20%) → reinvested into the vault (deepens liquidity)
 *      L4 (10%) → treasury QCT buyback + burn on Base
 *
 * VAULT TIERS (Temporal Taxonomy):
 *   Squire   (30d lock)  → 1.00× multiplier
 *   Knight   (90d lock)  → 1.18× multiplier
 *   Lord     (180d lock) → 1.38× multiplier
 *   Sovereign(365d lock) → 1.62× multiplier (≈ φ)
 *
 * SETUP (one-time, manual):
 *   1. Go to app.hyperliquid.xyz → Vaults → Create Vault
 *   2. Set description: "QCT Prosperity Vault — Sovereign Economy"
 *   3. Initial deposit: $100+ USDC
 *   4. Copy vault address → add to HL_VAULT_ADDRESS env var
 */

const axios    = require('axios');
const config   = require('./config');
const Kaprekar = require('../../src/Kaprekar');
const GoldenRatio = require('../../src/GoldenRatio');
const Nash     = require('../../src/Nash');

const PHI = 1.6180339887;

class VaultManager {
  constructor(hlClient) {
    this.hl             = hlClient;
    this.vaultAddress   = process.env.HL_VAULT_ADDRESS || null;
    this.tierDepositors = {};   // address → { tier, amount, lockedUntil, multiplier }
    this.pendingL2      = 0;
    this.pendingL3      = 0;
    this.pendingL4      = 0;
    this.l2ReleaseAt    = 0;
    this.l3ReleaseAt    = 0;
    this.l4ReleaseAt    = 0;
    this.totalDistributed = 0;
    this.kaprekar       = Kaprekar;
    this.releaseTimer   = null;
  }

  // ── Setup ──────────────────────────────────────────────────────────────────

  start() {
    if (!this.vaultAddress) {
      console.log('[VaultManager] No HL_VAULT_ADDRESS set. See setup instructions in this file.');
      console.log('[VaultManager] Running in tracking-only mode.');
    } else {
      console.log('[VaultManager] Vault:', this.vaultAddress);
    }
    this.releaseTimer = setInterval(() => this._checkReleases(), 60 * 1000);
  }

  stop() {
    if (this.releaseTimer) clearInterval(this.releaseTimer);
  }

  // ── Deposit tracking ────────────────────────────────────────────────────────

  registerDepositor(address, amountUSD, tierName) {
    const tier       = config.VAULT_TIERS[tierName.toUpperCase()] || config.VAULT_TIERS.SQUIRE;
    const lockedUntil = Date.now() + tier.lockDays * 24 * 60 * 60 * 1000;
    const multiplier  = GoldenRatio.multiplier
      ? GoldenRatio.multiplier(tier.lockDays / 30)
      : tier.multiplier;

    this.tierDepositors[address] = { tier: tierName, amountUSD, lockedUntil, multiplier };
    console.log(`[VaultManager] Depositor ${address} | Tier: ${tier.label} | ${tier.lockDays}d lock | ${multiplier.toFixed(3)}× multiplier`);
  }

  // ── Prosperity Cascade ─────────────────────────────────────────────────────

  processCascade(grossProfitUSD) {
    const C = config.CASCADE;
    const now = Date.now();

    const l1 = grossProfitUSD * C.L1_INSTANT;
    const l2 = grossProfitUSD * C.L2_24H;
    const l3 = grossProfitUSD * C.L3_48H;
    const l4 = grossProfitUSD * C.L4_72H;

    console.log(`[VaultManager] Cascade on $${grossProfitUSD.toFixed(4)}:`);
    console.log(`  L1 (instant, 40%): $${l1.toFixed(4)} → vault depositors`);
    console.log(`  L2 (24h,    30%): $${l2.toFixed(4)} → tier stakers`);
    console.log(`  L3 (48h,    20%): $${l3.toFixed(4)} → reinvest liquidity`);
    console.log(`  L4 (72h,    10%): $${l4.toFixed(4)} → QCT burn treasury`);

    // L1 — distributed to vault depositors by HL automatically
    this.totalDistributed += l1;

    // L2 — tracked for 24h payout to tier stakers
    this.pendingL2   += l2;
    this.l2ReleaseAt  = now + 24 * 60 * 60 * 1000;

    // L3 — queued for vault reinvestment
    this.pendingL3   += l3;
    this.l3ReleaseAt  = now + 48 * 60 * 60 * 1000;

    // L4 — queued for QCT buyback+burn on Base
    this.pendingL4   += l4;
    this.l4ReleaseAt  = now + 72 * 60 * 60 * 1000;

    return { l1, l2, l3, l4 };
  }

  async _checkReleases() {
    const now = Date.now();

    if (this.pendingL2 > 0 && now >= this.l2ReleaseAt) {
      await this._releaseL2();
    }
    if (this.pendingL3 > 0 && now >= this.l3ReleaseAt) {
      await this._releaseL3();
    }
    if (this.pendingL4 > 0 && now >= this.l4ReleaseAt) {
      await this._releaseL4();
    }
  }

  async _releaseL2() {
    const amt = this.pendingL2;
    this.pendingL2 = 0;
    console.log(`[VaultManager] L2 Release: $${amt.toFixed(4)} → distributing to ${Object.keys(this.tierDepositors).length} tier stakers`);

    // Calculate weighted shares using multipliers
    const depositors = Object.entries(this.tierDepositors);
    if (depositors.length === 0) return;

    const totalWeight = depositors.reduce((sum, [, d]) => sum + d.amountUSD * d.multiplier, 0);

    for (const [address, d] of depositors) {
      const share  = (d.amountUSD * d.multiplier) / totalWeight;
      const payout = amt * share;
      console.log(`  → ${address.slice(0,8)}... (${d.tier}): $${payout.toFixed(4)}`);
      this.totalDistributed += payout;
    }
  }

  async _releaseL3() {
    const amt = this.pendingL3;
    this.pendingL3 = 0;
    console.log(`[VaultManager] L3 Release: $${amt.toFixed(4)} → reinvesting into vault liquidity`);
    // In production: deposit back into vault via HL API
  }

  async _releaseL4() {
    const amt = this.pendingL4;
    this.pendingL4 = 0;
    console.log(`[VaultManager] L4 Release: $${amt.toFixed(4)} → triggering QCT buyback+burn on Base`);
    // Signals QCTHiveHL to execute buyback on Base chain
    this.emit && this.emit('burnTrigger', amt);
  }

  // ── Nash equilibrium rebalance ─────────────────────────────────────────────

  rebalanceCapital(totalEquity, currentSplits) {
    const adjusted = Nash.equilibriumAdjustment
      ? Nash.equilibriumAdjustment(currentSplits)
      : { arb: 0.60, vault: 0.30, reserve: 0.10 };

    console.log(`[VaultManager] Nash rebalance on $${totalEquity.toFixed(2)}:`);
    for (const [k, v] of Object.entries(adjusted)) {
      console.log(`  ${k}: $${(totalEquity * v).toFixed(2)} (${(v * 100).toFixed(0)}%)`);
    }
    return adjusted;
  }

  // ── Status ─────────────────────────────────────────────────────────────────

  getStatus() {
    return {
      vaultAddress:     this.vaultAddress,
      depositors:       Object.keys(this.tierDepositors).length,
      pendingL2:        this.pendingL2,
      pendingL3:        this.pendingL3,
      pendingL4:        this.pendingL4,
      totalDistributed: this.totalDistributed,
    };
  }
}

module.exports = VaultManager;
