services:
  - type: web
    name: kenostod-blockchain
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: BRIDGE_API_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_MODE
        value: live
      - key: WALLETCONNECT_PROJECT_ID
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: BANK_ENCRYPTION_KEY
        sync: false
      - key: DEPLOYER_PRIVATE_KEY
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: APP_URL
        sync: false

  - type: web
    name: kenostod-website
    env: static
    buildCommand: ""
    staticPublishPath: ./public
    pullRequestPreviewsEnabled: false
