// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/keno-token/InversionPillar.tsx": () => import("../components/mockups/keno-token/InversionPillar.tsx"),
  "./components/mockups/keno-token/KenoEmblem.tsx": () => import("../components/mockups/keno-token/KenoEmblem.tsx"),
  "./components/mockups/keno-token/NonagonPrism.tsx": () => import("../components/mockups/keno-token/NonagonPrism.tsx"),
  "./components/mockups/keno-token/SovereignMandala.tsx": () => import("../components/mockups/keno-token/SovereignMandala.tsx"),
  "./components/mockups/utlhook/InvestorPitch.tsx": () => import("../components/mockups/utlhook/InvestorPitch.tsx"),
  "./components/mockups/sagas/SagaI.tsx": () => import("../components/mockups/sagas/SagaI.tsx"),
  "./components/mockups/sagas/SagaII.tsx": () => import("../components/mockups/sagas/SagaII.tsx"),
  "./components/mockups/sagas/SagaIII.tsx": () => import("../components/mockups/sagas/SagaIII.tsx"),
  "./components/mockups/sagas/SagaIV.tsx": () => import("../components/mockups/sagas/SagaIV.tsx"),
  "./components/mockups/sagas/SagaV.tsx": () => import("../components/mockups/sagas/SagaV.tsx"),
  "./components/mockups/sagas/SagaVI.tsx": () => import("../components/mockups/sagas/SagaVI.tsx"),
  "./components/mockups/sagas/SagaVII.tsx": () => import("../components/mockups/sagas/SagaVII.tsx")
};
