// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/keno-token/InversionPillar.tsx": () => import("../components/mockups/keno-token/InversionPillar.tsx"),
  "./components/mockups/keno-token/KenoEmblem.tsx": () => import("../components/mockups/keno-token/KenoEmblem.tsx"),
  "./components/mockups/keno-token/NonagonPrism.tsx": () => import("../components/mockups/keno-token/NonagonPrism.tsx"),
  "./components/mockups/keno-token/SovereignMandala.tsx": () => import("../components/mockups/keno-token/SovereignMandala.tsx")
};
