/**
 * Queens Chariot Bot — The Hive Orchestrator & Protocol Revenue Engine 👑
 *
 * TWO INCOME STREAMS — the complete sovereign economy in one bot:
 *
 *   🐝 WORKER INCOME (Active)
 *      Aggregated from 6 worker bots trading external markets.
 *      KENO Flash Orb · Live Arb · Aegis Arb · Constitution Flash
 *      · Hyperliquid Funding · Drift Funding
 *
 *   👑 PROTOCOL INCOME (Passive — The Queen's Own Honey)
 *      Generated by QCT's 6 on-chain fee protocols on Base chain.
 *      Every QCT transfer → fees → flow through the Queen.
 *      Grows automatically with adoption. No trading required.
 *
 *      Income streams:
 *        1. Tithe & Triumph fees    — 2% on every QCT transfer
 *        2. Prosperity Cascade L1   — 40% instant holder redistribution
 *        3. SSWFR staking rebates   — Founder's stake-weighted pool share
 *        4. Guardian surcharges     — +3% on exploit-flagged wallets
 *        5. Alchemical AMM fees     — Volatility-responsive DEX fees
 *        6. Layer cascade releases  — Auto-triggered by the Queen herself
 *
 * 7 Constitutional Laws applied to BOTH income streams combined:
 *   1. Kaprekar   — 60% reinvest / 25% pocket / 15% QCT burn
 *   2. Benford    — Anomaly detection on profit patterns
 *   3. GoldenRatio— φ-ranked bot scoring
 *   4. Nash       — Capital rebalancing across worker bots
 *   5. Euler      — Compound growth projections
 *   6. Ramanujan  — $1,729 cumulative milestone alerts
 *   7. Inversion  — Value always flows DOWN to participants
 *
 * Pre-deployment: shows projected protocol revenue scenarios.
 * Post-deployment: live Base chain event monitoring via ethers.js.
 */

'use strict';

const axios  = require('axios');
const fs     = require('fs');
const path   = require('path');
const { ethers } = require('ethers');

// ── Mathematical constants ────────────────────────────────────────────────────
const PHI      = 1.6180339887;
const EULER    = Math.E;
const RAMANUJAN = 1729;

const KAPREKAR_REINVEST = 0.60;
const KAPREKAR_POCKET   = 0.25;
const KAPREKAR_BURN     = 0.15;

const NASH_TARGET_MONTHLY = 3000;
const POLL_INTERVAL_MS    = 60 * 1000;
const CHAIN_POLL_MS       = 30 * 1000;
const DAILY_REPORT_MS     = 24 * 60 * 60 * 1000;

// ── Base chain ────────────────────────────────────────────────────────────────
const BASE_RPC = 'https://mainnet.base.org';

// ── QCT contract ABI (events + view functions only) ───────────────────────────
const QCT_ABI = [
    // Events
    'event TithePaid(address indexed from, address indexed to, uint256 gross, uint256 fee)',
    'event ProsperityCascade(uint8 layer, uint256 amount, uint256 releaseAt)',
    'event CascadeReleased(uint8 layer, uint256 amount)',
    'event RebateClaimed(address indexed staker, uint256 amount)',
    'event GuardianAlert(address indexed suspect, uint256 confidence, uint256 surcharge)',
    'event Ramanujan1729(address indexed holder, uint256 totalReceived)',
    'event QueensBurn(uint256 amount, uint256 timestamp)',
    'event NashEquilibriumAdjusted(uint256 l1, uint256 l2, uint256 l3, uint256 l4)',
    'event SovereignTierAchieved(address indexed holder, uint8 tier)',

    // View functions
    'function getCascadeStatus() view returns (uint256 layer1Pending, uint256 layer2Amount, uint256 layer2At, uint256 layer3Amount, uint256 layer3At, uint256 layer4Amount, uint256 layer4At)',
    'function getProtocolStats() view returns (uint256 _sovereignPool, uint256 _guardianPool, uint256 _totalRedistributed, uint256 _totalStakeWeight, uint256 _holderCount, uint256 _stakerCount)',
    'function balanceOf(address account) view returns (uint256)',
    'function totalSupply() view returns (uint256)',
    'function sovereignPool() view returns (uint256)',
    'function pendingLayer1() view returns (uint256)',
    'function alchemicalFee() view returns (uint256)',
    'function currentVolatility() view returns (uint8)',

    // Write functions (public — anyone can call these)
    'function releaseCascade()',
    'function distributeLayer1()',
];

// ── Volume projection scenarios (pre-deployment planning) ─────────────────────
const VOLUME_SCENARIOS = [
    { label: 'Seed Stage',    dailyTxCount: 50,    avgTxUSD: 100  },
    { label: 'Early Growth',  dailyTxCount: 500,   avgTxUSD: 250  },
    { label: 'Active Market', dailyTxCount: 5000,  avgTxUSD: 500  },
    { label: 'Viral Phase',   dailyTxCount: 50000, avgTxUSD: 1000 },
];

class QueensChariotBotManager {
    constructor(workerBots = []) {
        this.workerBots = workerBots;

        // ── Queen core state ───────────────────────────────────────────────
        this.running    = false;
        this.startedAt  = null;
        this.scanCount  = 0;
        this.lastPollAt = null;

        // ── INCOME STREAM 1: Worker bot aggregation ────────────────────────
        this.botProfitDeltas   = {};
        this.botStartBaseline  = {};
        this.botProfits        = {};
        this.totalWorkerIncome = 0;

        // ── INCOME STREAM 2: QCT Protocol Revenue (The Queen's honey) ─────
        this.qctContractAddress  = null;
        this.qctContract         = null;
        this.qctProvider         = null;
        this.qctSigner           = null;
        this.qctDeployed         = false;
        this.qctPriceUSD         = 0.001;    // Pre-launch estimate; updated from DEX post-launch

        this.protocol = {
            titheFees:         0,   // QCT collected via Tithe & Triumph (2% transfers)
            cascadeL1:         0,   // QCT from Layer 1 instant redistribution
            sswfrRebates:      0,   // QCT from SSWFR staking rebates
            guardianSurcharge: 0,   // QCT from Guardian's Gambit surcharges
            alchemicalFees:    0,   // QCT from Alchemical AMM volatility fees
            totalQCT:          0,   // All protocol QCT accumulated
            totalUSD:          0,   // USD value (totalQCT × qctPriceUSD)
            feeEventCount:     0,   // Number of TithePaid events observed
            cascadeReleases:   0,   // Number of cascade layers released by Queen
            burnEvents:        0,   // Queen's Burn events observed
        };

        // On-chain live state (polled from contract)
        this.chainState = {
            sovereignPool:      0,  // Staker rebate pool (QCT)
            pendingLayer1:      0,  // Instant holder redistribution pending (QCT)
            cascadeL2Pending:   0,  // Layer 2 pending (QCT) — stakers, 24h
            cascadeL2ReadyAt:   0,
            cascadeL3Pending:   0,  // Layer 3 pending (QCT) — liquidity, 48h
            cascadeL3ReadyAt:   0,
            cascadeL4Pending:   0,  // Layer 4 pending (QCT) — treasury, 72h
            cascadeL4ReadyAt:   0,
            totalRedistributed: 0,
            holderCount:        0,
            stakerCount:        0,
            guardianPool:       0,
            totalSupply:        0,
        };

        this.pendingCascadeReleases = []; // Layers ready to release now

        // ── Grand total (worker + protocol) ───────────────────────────────
        this.totalProfit = 0; // Grand total — shown in dashboard

        // ── Law #1: Kaprekar split ────────────────────────────────────────
        this.kaprekarReinvest = 0;
        this.kaprekarPocket   = 0;
        this.kaprekarBurn     = 0;

        // ── Law #3: Golden Ratio ──────────────────────────────────────────
        this.phiScores  = {};
        this.phiRanking = [];

        // ── Law #4: Nash ──────────────────────────────────────────────────
        this.nashWeights      = {};
        this.nashLastRebalance = null;
        this.nashHistory      = [];

        // ── Law #5: Euler ─────────────────────────────────────────────────
        this.eulerDailyRate      = 0;
        this.eulerCurrentCapital = 500;
        this.eulerProjections    = {};

        // ── Law #6: Ramanujan ─────────────────────────────────────────────
        this.ramanujanNextTarget = RAMANUJAN;
        this.ramanujanHitCount   = 0;
        this.ramanujanHistory    = [];

        // ── Law #2: Benford ───────────────────────────────────────────────
        this.profitDeltas  = [];
        this.benfordAlert  = false;
        this.benfordReason = null;

        // ── Law #7: Inversion ─────────────────────────────────────────────
        this.inversionBreaches = [];

        // ── Signals ───────────────────────────────────────────────────────
        this.buybackSignals    = [];
        this.lastBuybackAt     = null;

        // ── Guardian ──────────────────────────────────────────────────────
        this.botSilenceAlerts = {};
        this.botWasRunning    = {};

        // ── Timers ────────────────────────────────────────────────────────
        this.pollTimer       = null;
        this.chainPollTimer  = null;
        this.dailyReportTimer = null;

        // ── Telegram ──────────────────────────────────────────────────────
        this.telegramToken  = process.env.KINGS_SHIELD_BOT_TOKEN || process.env.TELEGRAM_BOT_TOKEN;
        this.telegramChatId = process.env.SHIELD_ALERT_CHAT_ID;
        this.lastDailyReport = null;

        // ── Log ───────────────────────────────────────────────────────────
        this.log = [];

        // Try to load deployed QCT address immediately
        this._loadQCTDeployment();

        this._log('👑 Queens Chariot Bot initialized — Worker orchestrator + Protocol revenue engine');
        if (this.qctDeployed) {
            this._log(`   QCT contract found at ${this.qctContractAddress} — connecting to Base chain`);
        } else {
            this._log('   QCT not yet deployed — showing projections until deployment');
        }
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  START / STOP
    // ═══════════════════════════════════════════════════════════════════════

    start() {
        if (this.running) return { ok: false, msg: 'Queens Chariot Bot already running' };

        this.running    = true;
        this.startedAt  = Date.now();
        this.scanCount  = 0;

        this._snapshotBaselines();

        // Worker bot poll (60s)
        this.pollTimer = setInterval(() => this._poll(), POLL_INTERVAL_MS);
        this._poll();

        // Chain state poll (30s)
        this.chainPollTimer = setInterval(() => this._pollChainState(), CHAIN_POLL_MS);
        this._pollChainState();

        // Connect to Base and subscribe to QCT events
        if (this.qctDeployed) {
            this._connectBaseChain();
        }

        // Daily Telegram report
        this.dailyReportTimer = setInterval(() => this._sendDailyReport(), DAILY_REPORT_MS);

        this._log('👑 Queens Chariot Bot STARTED — Dual income engine active');
        this._telegram(
            `👑 <b>Queens Chariot — Hive & Protocol Engine ONLINE</b>\n\n` +
            `The Queen is now generating income from <b>two streams</b>:\n\n` +
            `🐝 <b>Stream 1 — Worker Income (Active)</b>\n` +
            `   6 worker bots monitored across BSC · Solana · Hyperliquid\n\n` +
            `👑 <b>Stream 2 — Protocol Income (Passive)</b>\n` +
            (this.qctDeployed
                ? `   ✅ QCT contract live — watching Base chain events\n`
                  + `   Every QCT transfer generates fee income automatically\n`
                : `   ⏳ QCT awaiting deployment — projections shown\n`
                  + `   Protocol income activates the moment QCT goes live on Base\n`)
            + `\n🎯 Nash Target: $${NASH_TARGET_MONTHLY.toLocaleString()}/month\n`
            + `⚖️  7 Constitutional Laws: ACTIVE on both streams\n\n`
            + `<i>"The workers bring nectar. The Queen makes the honey."</i>`
        );

        return { ok: true, msg: 'Queens Chariot Bot started — dual income engine running' };
    }

    stop() {
        if (!this.running) return { ok: false, msg: 'Queens Chariot Bot is not running' };

        this.running = false;
        if (this.pollTimer)         { clearInterval(this.pollTimer);        this.pollTimer = null; }
        if (this.chainPollTimer)    { clearInterval(this.chainPollTimer);   this.chainPollTimer = null; }
        if (this.dailyReportTimer)  { clearInterval(this.dailyReportTimer); this.dailyReportTimer = null; }

        // Remove contract event listeners
        if (this.qctContract) {
            try { this.qctContract.removeAllListeners(); } catch {}
        }

        const summary = this._buildHiveSummary();
        this._log('👑 Queens Chariot Bot STOPPED');
        this._telegram(`👑 <b>Queens Chariot Bot — OFFLINE</b>\n\n${summary}\n\n<i>The Queen rests. The hive remembers.</i>`);

        return { ok: true, msg: 'Queens Chariot Bot stopped', summary };
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  QCT DEPLOYMENT LOADER
    // ═══════════════════════════════════════════════════════════════════════

    _loadQCTDeployment() {
        try {
            const depPath = path.join(__dirname, '..', 'queens-chariot', 'deployments', 'qct-base.json');
            if (fs.existsSync(depPath)) {
                const dep = JSON.parse(fs.readFileSync(depPath, 'utf8'));
                if (dep.contractAddress && ethers.isAddress(dep.contractAddress)) {
                    this.qctContractAddress = dep.contractAddress;
                    this.qctDeployed        = true;
                    return true;
                }
            }
        } catch {}
        return false;
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  BASE CHAIN CONNECTION — live event subscriptions
    // ═══════════════════════════════════════════════════════════════════════

    async _connectBaseChain() {
        try {
            this.qctProvider = new ethers.JsonRpcProvider(BASE_RPC);
            await this.qctProvider.getBlockNumber(); // Connectivity check

            this.qctContract = new ethers.Contract(
                this.qctContractAddress,
                QCT_ABI,
                this.qctProvider
            );

            // ── Subscribe to QCT events ──────────────────────────────────

            // 1. Every transfer generates a Tithe fee
            this.qctContract.on('TithePaid', (from, to, gross, fee) => {
                const grossQCT = parseFloat(ethers.formatEther(gross));
                const feeQCT   = parseFloat(ethers.formatEther(fee));
                this.protocol.titheFees    += feeQCT;
                this.protocol.totalQCT     += feeQCT;
                this.protocol.feeEventCount++;
                this.profitDeltas.push(feeQCT * this.qctPriceUSD); // For Benford
                if (this.profitDeltas.length > 150) this.profitDeltas.shift();
                this._updateProtocolUSD();
                this._log(`💰 TithePaid: ${feeQCT.toFixed(4)} QCT fee on ${grossQCT.toFixed(2)} QCT transfer`);
            });

            // 2. Cascade releases — direct protocol income materialising
            this.qctContract.on('CascadeReleased', (layer, amount) => {
                const amtQCT = parseFloat(ethers.formatEther(amount));
                if (layer === 1n) {
                    this.protocol.cascadeL1 += amtQCT;
                    this.protocol.totalQCT  += amtQCT;
                    this.protocol.cascadeReleases++;
                    this._updateProtocolUSD();
                    this._log(`🌊 Cascade L1 released: ${amtQCT.toFixed(4)} QCT → holder redistribution`);
                }
            });

            // 3. Staking rebates claimed
            this.qctContract.on('RebateClaimed', (staker, amount) => {
                const amtQCT = parseFloat(ethers.formatEther(amount));
                this.protocol.sswfrRebates += amtQCT;
                this.protocol.totalQCT     += amtQCT;
                this._updateProtocolUSD();
                this._log(`🎁 SSWFR rebate: ${amtQCT.toFixed(4)} QCT claimed by ${staker.slice(0,10)}...`);
            });

            // 4. Guardian surcharges (fee portion of exploit protection)
            this.qctContract.on('GuardianAlert', (suspect, confidence, surcharge) => {
                this.protocol.guardianSurcharge += parseFloat(ethers.formatEther(surcharge));
                this._log(`🛡️  Guardian alert: ${suspect.slice(0,10)}... flagged (${confidence}% confidence)`);
                this._telegram(
                    `🛡️ <b>QCT Guardian Alert</b>\n\n` +
                    `Exploit attempt flagged on Base chain.\n` +
                    `Suspect: <code>${suspect}</code>\n` +
                    `Confidence: ${confidence}%\n` +
                    `Surcharge: ${ethers.formatEther(surcharge)} QCT routed to victims`
                );
            });

            // 5. Ramanujan milestone on-chain (echoes our off-chain tracker)
            this.qctContract.on('Ramanujan1729', (holder, totalReceived) => {
                this._log(`🌟 On-chain Ramanujan milestone: holder ${holder.slice(0,10)}... crossed 1729 QCT`);
                this._telegram(`🌟 <b>On-Chain Ramanujan Milestone</b>\n\nHolder <code>${holder}</code> has received 1,729 QCT in lifetime rebates.\n\nThe Hardy-Ramanujan number lives on Base chain.`);
            });

            // 6. Queen's Burn observed
            this.qctContract.on('QueensBurn', (amount, timestamp) => {
                this.protocol.burnEvents++;
                this._log(`🔥 Queen's Burn: ${ethers.formatEther(amount)} QCT burned on-chain`);
            });

            this._log(`✅ Connected to Base chain — watching QCT at ${this.qctContractAddress}`);
            this._telegram(
                `✅ <b>QCT Protocol Engine Connected</b>\n\n` +
                `Now receiving live fee events from Base chain.\n` +
                `Contract: <code>${this.qctContractAddress}</code>\n\n` +
                `Every QCT transfer is now generating protocol income for the Queen.`
            );

        } catch (err) {
            this._log(`⚠ Base chain connection failed: ${err.message} — will retry on next chain poll`);
        }
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  CHAIN STATE POLL — reads on-chain state every 30 seconds
    // ═══════════════════════════════════════════════════════════════════════

    async _pollChainState() {
        // If QCT just deployed but we weren't connected — check now
        if (!this.qctDeployed && this._loadQCTDeployment()) {
            this._log('🎉 QCT deployment detected! Connecting to Base chain...');
            await this._connectBaseChain();
        }

        if (!this.qctContract) return;

        try {
            // Pull cascade status
            const [l1, l2, l2At, l3, l3At, l4, l4At] = await this.qctContract.getCascadeStatus();
            this.chainState.pendingLayer1   = parseFloat(ethers.formatEther(l1));
            this.chainState.cascadeL2Pending = parseFloat(ethers.formatEther(l2));
            this.chainState.cascadeL2ReadyAt = Number(l2At) * 1000;
            this.chainState.cascadeL3Pending = parseFloat(ethers.formatEther(l3));
            this.chainState.cascadeL3ReadyAt = Number(l3At) * 1000;
            this.chainState.cascadeL4Pending = parseFloat(ethers.formatEther(l4));
            this.chainState.cascadeL4ReadyAt = Number(l4At) * 1000;

            // Pull protocol stats
            const [sPool, gPool, totalRedist, , hCount, sCount] = await this.qctContract.getProtocolStats();
            this.chainState.sovereignPool      = parseFloat(ethers.formatEther(sPool));
            this.chainState.guardianPool       = parseFloat(ethers.formatEther(gPool));
            this.chainState.totalRedistributed = parseFloat(ethers.formatEther(totalRedist));
            this.chainState.holderCount        = Number(hCount);
            this.chainState.stakerCount        = Number(sCount);

            // Auto-release cascade layers that are ready (public function, Queen calls it)
            await this._autoReleaseCascade();

        } catch (err) {
            this._log(`⚠ Chain poll error: ${err.message}`);
        }
    }

    // Auto-trigger cascade releases when layers are ready
    async _autoReleaseCascade() {
        if (!this.qctContract || !this.qctSigner) return;

        // ── Cooldown: only attempt once every 10 minutes to stop hammering ──
        const now = Date.now();
        const COOLDOWN_MS = 10 * 60 * 1000;
        if (this._lastCascadeAttempt && (now - this._lastCascadeAttempt) < COOLDOWN_MS) return;

        const needsRelease = (
            (this.chainState.cascadeL2Pending > 0 && now >= this.chainState.cascadeL2ReadyAt) ||
            (this.chainState.cascadeL3Pending > 0 && now >= this.chainState.cascadeL3ReadyAt) ||
            (this.chainState.cascadeL4Pending > 0 && now >= this.chainState.cascadeL4ReadyAt)
        );
        if (!needsRelease) return;

        // ── Pre-flight: simulate before spending gas ──
        try {
            const contractWithSigner = this.qctContract.connect(this.qctSigner);
            try {
                await contractWithSigner.releaseCascade.estimateGas();
            } catch (simErr) {
                this._lastCascadeAttempt = now;
                this._log(`⛔ Cascade pre-flight failed — nothing to release yet. No gas spent.`);
                return;
            }

            this._lastCascadeAttempt = now;
            const tx = await contractWithSigner.releaseCascade();
            await tx.wait(1);
            this.protocol.cascadeReleases++;
            this._log(`🌊 Queen auto-released cascade layers — tx ${tx.hash}`);
            this._telegram(`🌊 <b>Cascade Released by Queen</b>\n\nThe Queen triggered a Prosperity Cascade release.\nTx: <code>${tx.hash}</code>`);
        } catch (err) {
            this._lastCascadeAttempt = now;
            this._log(`⚠ Cascade release error: ${err.message}`);
        }
    }

    _updateProtocolUSD() {
        this.protocol.totalUSD = this.protocol.totalQCT * this.qctPriceUSD;
        // Update grand total
        this.totalProfit = this.totalWorkerIncome + this.protocol.totalUSD;
        // Recalculate Kaprekar on combined total
        this.kaprekarReinvest = this.totalProfit * KAPREKAR_REINVEST;
        this.kaprekarPocket   = this.totalProfit * KAPREKAR_POCKET;
        this.kaprekarBurn     = this.totalProfit * KAPREKAR_BURN;
        const dust = this.totalProfit - this.kaprekarReinvest - this.kaprekarPocket - this.kaprekarBurn;
        this.kaprekarReinvest += dust;
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  WORKER BOT POLL — runs every 60 seconds
    // ═══════════════════════════════════════════════════════════════════════

    _poll() {
        if (!this.running) return;
        this.scanCount++;
        this.lastPollAt = Date.now();

        try {
            const snapshot = this._gatherHiveStatus();
            this._updateWorkerDeltas(snapshot);
            this._applyGoldenRatio();
            this._applyNash();
            this._applyEuler();
            this._checkRamanujan();
            this._applyBenford();
            this._enforceInversion();
            this._guardianCheck(snapshot);
            this._checkBuybackSignal();
        } catch (err) {
            this._log(`⚠ Hive poll error: ${err.message}`);
        }
    }

    _gatherHiveStatus() {
        const snapshot = {};
        for (const bot of this.workerBots) {
            try {
                const s = bot.manager.getStatus();
                snapshot[bot.id] = {
                    running:    !!s.running,
                    profit:     parseFloat(s.totalProfit || 0),
                    tradeCount: parseInt(s.tradeCount    || 0),
                    scanCount:  parseInt(s.scanCount     || 0),
                    chain:      bot.chain,
                    name:       bot.name,
                    emoji:      bot.emoji,
                };
            } catch {
                snapshot[bot.id] = { running: false, profit: 0, tradeCount: 0, scanCount: 0,
                                     chain: bot.chain, name: bot.name, emoji: bot.emoji };
            }
        }
        return snapshot;
    }

    _snapshotBaselines() {
        for (const bot of this.workerBots) {
            try {
                const s = bot.manager.getStatus();
                const p = parseFloat(s.totalProfit || 0);
                this.botStartBaseline[bot.id] = p;
                this.botProfits[bot.id]       = p;
                this.botProfitDeltas[bot.id]  = 0;
            } catch {
                this.botStartBaseline[bot.id] = 0;
                this.botProfits[bot.id]       = 0;
                this.botProfitDeltas[bot.id]  = 0;
            }
        }
    }

    _updateWorkerDeltas(snapshot) {
        let newDelta = 0;
        for (const [id, data] of Object.entries(snapshot)) {
            const baseline  = this.botStartBaseline[id] || 0;
            const delta     = Math.max(0, data.profit - baseline);
            const prevDelta = this.botProfitDeltas[id]  || 0;
            const increment = delta - prevDelta;

            this.botProfitDeltas[id] = delta;
            this.botProfits[id]      = data.profit;

            if (increment > 0) {
                newDelta += increment;
                this.profitDeltas.push(increment);
                if (this.profitDeltas.length > 150) this.profitDeltas.shift();
            }
        }
        if (newDelta > 0) {
            this.totalWorkerIncome += newDelta;
            this._updateProtocolUSD(); // Recalculates totalProfit grand total
            this._log(`🐝 Workers earned +$${newDelta.toFixed(4)} | Worker total: $${this.totalWorkerIncome.toFixed(2)}`);
        }
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  7 CONSTITUTIONAL LAWS
    // ═══════════════════════════════════════════════════════════════════════

    _applyBenford() {
        const n = this.profitDeltas.length;
        if (n < 20) return;
        const checkN = Math.min(n, 100);
        let d1 = 0;
        for (let i = n - checkN; i < n; i++) {
            let leadStr = Math.abs(this.profitDeltas[i]).toFixed(6).replace('.', '').replace(/^0+/, '');
            if (leadStr && leadStr[0] === '1') d1++;
        }
        const pct = (d1 / checkN) * 100;
        const wasAlert = this.benfordAlert;
        if (pct < 8 || pct > 65) {
            this.benfordAlert  = true;
            this.benfordReason = `Leading-1 rate = ${pct.toFixed(1)}% (Benford expects ~30%). Possible wash trading or manipulation.`;
            if (!wasAlert) {
                this._log(`⚠ Benford anomaly: ${this.benfordReason}`);
                this._telegram(`⚠️ <b>Benford Anomaly Detected</b>\n\n${this.benfordReason}`);
            }
        } else {
            this.benfordAlert  = false;
            this.benfordReason = null;
        }
    }

    _applyGoldenRatio() {
        const days = this.startedAt ? (Date.now() - this.startedAt) / 86400000 : 1;
        const scores = {};
        for (const [id, delta] of Object.entries(this.botProfitDeltas)) {
            scores[id] = delta * Math.pow(PHI, days / 30);
        }
        this.phiScores  = scores;
        this.phiRanking = Object.entries(scores).sort(([,a],[,b]) => b - a).map(([id]) => id);
    }

    _applyNash() {
        const total  = Object.values(this.botProfitDeltas).reduce((s, v) => s + v, 0);
        const floor  = Math.max(5, Math.floor(100 / Math.max(1, this.workerBots.length) / 2));
        const weights = {};

        if (total <= 0) {
            for (const bot of this.workerBots) weights[bot.id] = Math.floor(100 / this.workerBots.length);
        } else {
            let rem = 100;
            const sorted = [...this.workerBots].sort(
                (a, b) => (this.botProfitDeltas[b.id] || 0) - (this.botProfitDeltas[a.id] || 0)
            );
            for (let i = 0; i < sorted.length; i++) {
                const bot   = sorted[i];
                const delta = this.botProfitDeltas[bot.id] || 0;
                const share = Math.round((delta / total) * 100);
                const w     = Math.max(floor, Math.min(share, rem - floor * (sorted.length - i - 1)));
                weights[bot.id] = w;
                rem -= w;
            }
        }

        const changed = Object.keys(weights).some(
            id => Math.abs((weights[id] || 0) - (this.nashWeights[id] || 0)) > 5
        );
        if (changed && this.scanCount > 1) {
            this.nashHistory.unshift({ timestamp: Date.now(), weights: { ...weights } });
            if (this.nashHistory.length > 10) this.nashHistory.pop();
        }

        this.nashWeights       = weights;
        this.nashLastRebalance = Date.now();
    }

    _applyEuler() {
        const days = this.startedAt ? (Date.now() - this.startedAt) / 86400000 : 0.001;
        if (this.totalProfit <= 0 || days < 0.1) return;

        this.eulerDailyRate = Math.log(1 + this.totalProfit / 500) / days;
        const mr = this.eulerDailyRate * 30;

        const proj = {};
        for (const mo of [1, 3, 6, 12, 24]) {
            proj[mo] = 500 * Math.pow(EULER, mr * mo);
        }
        this.eulerProjections    = proj;
        this.eulerCurrentCapital = 500 + this.totalProfit * KAPREKAR_REINVEST;
    }

    _checkRamanujan() {
        if (this.totalProfit >= this.ramanujanNextTarget) {
            this.ramanujanHitCount++;
            const mult = this.ramanujanHitCount;
            this.ramanujanHistory.push({ milestone: mult, amount: this.totalProfit, timestamp: Date.now() });
            this.ramanujanNextTarget = RAMANUJAN * (mult + 1);
            this._log(`🌟 Ramanujan Milestone #${mult}: $${this.totalProfit.toFixed(2)}`);
            this._telegram(
                `🌟 <b>Ramanujan Milestone #${mult} Achieved!</b>\n\n` +
                `Combined hive + protocol income: <b>$${this.totalProfit.toFixed(2)}</b>\n` +
                `Crossed $${(RAMANUJAN * mult).toLocaleString()} threshold.\n\n` +
                `Next milestone: $${(RAMANUJAN * (mult + 1)).toLocaleString()}`
            );
        }
    }

    _enforceInversion() {
        if (this.totalProfit <= 0) return;
        const participantShare = this.kaprekarReinvest + this.kaprekarPocket;
        const protocolShare    = this.kaprekarBurn;
        if (participantShare < protocolShare) {
            this.inversionBreaches.push({ timestamp: Date.now(), participantShare, protocolShare });
            this._log(`⚠ Inversion breach: protocol > participant`);
        }
    }

    _guardianCheck(snapshot) {
        const now = Date.now();
        for (const bot of this.workerBots) {
            const data      = snapshot[bot.id] || {};
            const wasRunning = this.botWasRunning[bot.id] || false;
            if (wasRunning && !data.running) {
                const last = this.botSilenceAlerts[bot.id] || 0;
                if (now - last > 30 * 60 * 1000) {
                    this.botSilenceAlerts[bot.id] = now;
                    this._telegram(
                        `🚨 <b>Worker Bot Offline</b>\n\n${bot.emoji} ${bot.name} went silent.\n` +
                        `Nash weight: ${this.nashWeights[bot.id] || 0}%\n` +
                        `Visit Bots dashboard to restart.`
                    );
                }
            }
            this.botWasRunning[bot.id] = data.running;
        }
    }

    _checkBuybackSignal() {
        const now         = Date.now();
        const timeSinceLast = this.lastBuybackAt ? now - this.lastBuybackAt : Infinity;
        if (this.totalProfit >= 100 && this.kaprekarBurn >= 15 && timeSinceLast > DAILY_REPORT_MS) {
            this.lastBuybackAt = now;
            this.buybackSignals.push({ timestamp: now, totalProfit: this.totalProfit, burnAmount: this.kaprekarBurn });
            this._telegram(
                `💎 <b>QCT Buyback & Burn Signal</b>\n\n` +
                `Combined hive income: <b>$${this.totalProfit.toFixed(2)}</b>\n` +
                `Kaprekar 15% burn allocation: <b>$${this.kaprekarBurn.toFixed(2)}</b>\n\n` +
                `Buy QCT on Aerodrome / Uniswap V3 (Base) and burn.\n` +
                `<i>Every burn makes the Chariot lighter and faster.</i>`
            );
        }
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  PRE-DEPLOYMENT PROJECTIONS
    // ═══════════════════════════════════════════════════════════════════════

    _buildProjections() {
        const QCT_FEE_RATE = 0.02; // 2% base Tithe & Triumph fee
        return VOLUME_SCENARIOS.map(sc => {
            const dailyVolumeUSD  = sc.dailyTxCount * sc.avgTxUSD;
            const dailyFeesUSD    = dailyVolumeUSD * QCT_FEE_RATE;
            const monthlyFeesUSD  = dailyFeesUSD * 30;
            // Fee split: 40% to holders, 30% to stakers, 20% liquidity, 10% treasury
            const founderShareUSD = monthlyFeesUSD * 0.25; // Kaprekar 25% pocket
            return {
                label:           sc.label,
                dailyTxCount:    sc.dailyTxCount,
                avgTxUSD:        sc.avgTxUSD,
                dailyVolumeUSD,
                dailyFeesUSD:    parseFloat(dailyFeesUSD.toFixed(2)),
                monthlyFeesUSD:  parseFloat(monthlyFeesUSD.toFixed(2)),
                founderMonthlyUSD: parseFloat(founderShareUSD.toFixed(2)),
            };
        });
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  REPORTS
    // ═══════════════════════════════════════════════════════════════════════

    _sendDailyReport() {
        this.lastDailyReport = Date.now();
        this._telegram(`👑 <b>Daily Hive Report</b>\n\n${this._buildHiveSummary()}`);
    }

    _buildHiveSummary() {
        const lines = [];

        lines.push(`━━━━━━━━━━━━━━━━━━━━━━━━━━`);
        lines.push(`🐝 <b>WORKER INCOME (Active)</b>`);
        lines.push(`━━━━━━━━━━━━━━━━━━━━━━━━━━`);
        for (const bot of this.workerBots) {
            const delta   = this.botProfitDeltas[bot.id] || 0;
            const w       = this.nashWeights[bot.id]      || 0;
            const rank    = this.phiRanking.indexOf(bot.id) + 1;
            const status  = this.botWasRunning[bot.id] ? '🟢' : '🔴';
            lines.push(`${status} ${bot.emoji} ${bot.name}`);
            lines.push(`   $${delta.toFixed(2)} profit | Nash ${w}% | φ-rank #${rank}`);
        }
        lines.push(`Total worker income: <b>$${this.totalWorkerIncome.toFixed(2)}</b>`);

        lines.push(``);
        lines.push(`━━━━━━━━━━━━━━━━━━━━━━━━━━`);
        lines.push(`👑 <b>PROTOCOL INCOME (The Queen's Honey)</b>`);
        lines.push(`━━━━━━━━━━━━━━━━━━━━━━━━━━`);

        if (!this.qctDeployed) {
            lines.push(`⏳ QCT awaiting deployment on Base chain`);
            lines.push(`   Protocol income activates on launch`);
            lines.push(``);
            lines.push(`📊 <b>Projected Protocol Revenue Scenarios:</b>`);
            const proj = this._buildProjections();
            for (const sc of proj) {
                lines.push(`  📌 <b>${sc.label}</b>`);
                lines.push(`     Volume: $${sc.dailyVolumeUSD.toLocaleString()}/day`);
                lines.push(`     Fees: $${sc.dailyFeesUSD}/day → $${sc.monthlyFeesUSD.toLocaleString()}/mo`);
                lines.push(`     Your 25%: <b>$${sc.founderMonthlyUSD.toLocaleString()}/mo</b>`);
            }
        } else {
            lines.push(`✅ QCT live on Base: <code>${this.qctContractAddress.slice(0,18)}...</code>`);
            lines.push(`   🪙 Tithe fees collected:  ${this.protocol.titheFees.toFixed(2)} QCT ($${(this.protocol.titheFees * this.qctPriceUSD).toFixed(2)})`);
            lines.push(`   🌊 Cascade L1 released:   ${this.protocol.cascadeL1.toFixed(2)} QCT ($${(this.protocol.cascadeL1 * this.qctPriceUSD).toFixed(2)})`);
            lines.push(`   🎁 SSWFR rebates:         ${this.protocol.sswfrRebates.toFixed(2)} QCT ($${(this.protocol.sswfrRebates * this.qctPriceUSD).toFixed(2)})`);
            lines.push(`   🛡️  Guardian surcharges:   ${this.protocol.guardianSurcharge.toFixed(2)} QCT`);
            lines.push(`   📅 Fee events: ${this.protocol.feeEventCount} | Cascade releases: ${this.protocol.cascadeReleases}`);
            lines.push(`   💰 Total protocol income: <b>${this.protocol.totalQCT.toFixed(2)} QCT ($${this.protocol.totalUSD.toFixed(2)})</b>`);
            lines.push(``);
            lines.push(`📡 <b>On-Chain Cascade Status:</b>`);
            lines.push(`   L1 pending: ${this.chainState.pendingLayer1.toFixed(2)} QCT (instant holders)`);
            lines.push(`   L2 pending: ${this.chainState.cascadeL2Pending.toFixed(2)} QCT (stakers, 24h)`);
            lines.push(`   L3 pending: ${this.chainState.cascadeL3Pending.toFixed(2)} QCT (liquidity, 48h)`);
            lines.push(`   L4 pending: ${this.chainState.cascadeL4Pending.toFixed(2)} QCT (treasury, 72h)`);
            lines.push(`   Holders: ${this.chainState.holderCount} | Stakers: ${this.chainState.stakerCount}`);
        }

        lines.push(``);
        lines.push(`━━━━━━━━━━━━━━━━━━━━━━━━━━`);
        lines.push(`💰 <b>GRAND TOTAL: $${this.totalProfit.toFixed(2)}</b>`);
        lines.push(`━━━━━━━━━━━━━━━━━━━━━━━━━━`);

        lines.push(``);
        lines.push(`⚖️ <b>Kaprekar Split (Law #1):</b>`);
        lines.push(`   🔄 60% reinvest:  $${this.kaprekarReinvest.toFixed(2)}`);
        lines.push(`   💵 25% pocket:    $${this.kaprekarPocket.toFixed(2)}`);
        lines.push(`   🔥 15% QCT burn: $${this.kaprekarBurn.toFixed(2)}`);

        if (this.eulerDailyRate > 0 && Object.keys(this.eulerProjections).length > 0) {
            lines.push(``);
            lines.push(`📈 <b>Euler Compound Path (Law #5):</b>`);
            const monthlyNow = (this.eulerCurrentCapital * this.eulerDailyRate * 30).toFixed(0);
            lines.push(`   Monthly income now: ~$${monthlyNow}`);
            for (const [mo, cap] of Object.entries(this.eulerProjections)) {
                const inc  = (cap * this.eulerDailyRate * 30).toFixed(0);
                const flag = parseFloat(inc) >= NASH_TARGET_MONTHLY ? ' 🎯 Financial Freedom' : '';
                lines.push(`   ${mo}mo → $${Math.round(cap).toLocaleString()} → ~$${inc}/mo${flag}`);
            }
        }

        lines.push(``);
        const ramPct = Math.min(100, (this.totalProfit / this.ramanujanNextTarget * 100)).toFixed(1);
        lines.push(`🌟 Ramanujan: $${this.totalProfit.toFixed(2)} / $${this.ramanujanNextTarget.toLocaleString()} (${ramPct}%)`);
        lines.push(`✅ Benford: ${this.benfordAlert ? '⚠ ANOMALY — ' + this.benfordReason : 'Clean'}`);
        lines.push(`🔄 Inversion: ${this.inversionBreaches.length === 0 ? 'Value flowing DOWN ✅' : `⚠ ${this.inversionBreaches.length} breach(es)`}`);
        lines.push(`🔍 Hive scans: ${this.scanCount} | Uptime: ${this._uptime()}`);

        return lines.join('\n');
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  PUBLIC API
    // ═══════════════════════════════════════════════════════════════════════

    rebalance() {
        this._applyGoldenRatio();
        this._applyNash();
        return { ok: true, nashWeights: this.nashWeights, phiRanking: this.phiRanking };
    }

    sendReport() {
        this._sendDailyReport();
        return { ok: true, msg: 'Hive report sent to Telegram' };
    }

    getStatus() {
        return {
            running:             this.running,
            startedAt:           this.startedAt,
            scanCount:           this.scanCount,
            lastPollAt:          this.lastPollAt,
            uptime:              this._uptime(),
            workerBotCount:      this.workerBots.length,

            // Income streams
            totalWorkerIncome:   this.totalWorkerIncome,
            totalProtocolIncome: this.protocol.totalUSD,
            totalProfit:         this.totalProfit,          // Grand total (dashboard-compatible)

            // Protocol revenue breakdown
            protocolQCT:         this.protocol.totalQCT,
            protocolFeeEvents:   this.protocol.feeEventCount,
            protocolDeployed:    this.qctDeployed,
            protocolAddress:     this.qctContractAddress,
            protocol:            this.protocol,
            chainState:          this.chainState,

            // Constitutional Laws
            kaprekarReinvest:    this.kaprekarReinvest,
            kaprekarPocket:      this.kaprekarPocket,
            kaprekarBurn:        this.kaprekarBurn,
            phiRanking:          this.phiRanking,
            phiScores:           this.phiScores,
            nashWeights:         this.nashWeights,
            eulerDailyRate:      this.eulerDailyRate,
            eulerCurrentCapital: this.eulerCurrentCapital,
            eulerProjections:    this.eulerProjections,
            ramanujanProgress:   `$${this.totalProfit.toFixed(2)} / $${this.ramanujanNextTarget.toLocaleString()}`,
            ramanujanPct:        Math.min(100, this.totalProfit / this.ramanujanNextTarget * 100).toFixed(1),
            ramanujanHitCount:   this.ramanujanHitCount,
            benfordAlert:        this.benfordAlert,
            inversionBreaches:   this.inversionBreaches.length,
            buybackSignalCount:  this.buybackSignals.length,
            lastBuybackAt:       this.lastBuybackAt,

            // Worker bots
            botProfitDeltas:     this.botProfitDeltas,

            // Pre-deployment projections
            projections:         !this.qctDeployed ? this._buildProjections() : null,

            log:                 this.log.slice(-20),
        };
    }

    getFullReport() {
        return {
            ok:                true,
            summary:           this._buildHiveSummary(),
            status:            this.getStatus(),
            nashHistory:       this.nashHistory,
            ramanujanHistory:  this.ramanujanHistory,
            buybackSignals:    this.buybackSignals.slice(-5),
            inversionBreaches: this.inversionBreaches.slice(-5),
            projections:       this._buildProjections(),
        };
    }

    // ═══════════════════════════════════════════════════════════════════════
    //  HELPERS
    // ═══════════════════════════════════════════════════════════════════════

    _uptime() {
        if (!this.startedAt) return '0m';
        const ms  = Date.now() - this.startedAt;
        const h   = Math.floor(ms / 3600000);
        const m   = Math.floor((ms % 3600000) / 60000);
        return h > 0 ? `${h}h ${m}m` : `${m}m`;
    }

    _log(msg) {
        const entry = `[${new Date().toISOString().slice(11,19)}] ${msg}`;
        console.log(`[QueensChariot] ${entry}`);
        this.log.push(entry);
        if (this.log.length > 100) this.log.shift();
    }

    async _telegram(text) {
        if (!this.telegramToken || !this.telegramChatId) return;
        try {
            await axios.post(
                `https://api.telegram.org/bot${this.telegramToken}/sendMessage`,
                { chat_id: this.telegramChatId, text, parse_mode: 'HTML' },
                { timeout: 10000 }
            );
        } catch {}
    }
}

module.exports = QueensChariotBotManager;

if (require.main === module) {
  process.on('unhandledRejection', (err) => {
    console.error('[QueensChariot] Unhandled rejection (process stays alive):', err && err.message);
  });
  const bot = new QueensChariotBotManager();
  function tryStart() {
    try {
      const result = bot.start();
      const p = result && typeof result.then === 'function' ? result : Promise.resolve(result);
      p.catch(err => {
        console.error('[QueensChariot] Start failed, retrying in 90s:', err && err.message);
        setTimeout(tryStart, 90_000);
      }).then(res => {
        if (res && !res.ok) {
          console.error('[QueensChariot] Start not-ok, retrying in 90s:', res.msg);
          setTimeout(tryStart, 90_000);
        }
      });
    } catch (err) {
      console.error('[QueensChariot] Start threw, retrying in 90s:', err.message);
      setTimeout(tryStart, 90_000);
    }
  }
  tryStart();
  process.on('SIGTERM', () => { try { bot.stop(); } catch(_) {} process.exit(0); });
  process.on('SIGINT',  () => { try { bot.stop(); } catch(_) {} process.exit(0); });
}
