const crypto = require('crypto');

/**
 * Residual Value Token (RVT)
 * 
 * RVTs are special tokens linked to specific computational outputs (AI models, simulations).
 * They represent a claim on perpetual royalties generated by the commercial use of that output.
 */
class ResidualValueToken {
    constructor(jobId, minedBy, blockHeight, outputType, metadata = {}) {
        this.rvtId = this.generateRVTId(jobId, minedBy, blockHeight);
        this.jobId = jobId; // Links to the computational job
        this.minedBy = minedBy; // Miner who validated the computation
        this.blockHeight = blockHeight; // Block where this RVT was created
        this.outputType = outputType; // e.g., 'AI_MODEL', 'SIMULATION', 'DATA_ANALYTICS'
        this.metadata = metadata; // Additional info (model name, client, etc.)
        this.createdAt = Date.now();
        this.totalRoyaltiesCollected = 0; // Track lifetime royalties
        this.totalRoyaltiesDistributed = 0; // Track what's been paid to holder
        this.isActive = true; // Can be deactivated if licensed product is deprecated
    }

    generateRVTId(jobId, minedBy, blockHeight) {
        const data = `${jobId}-${minedBy}-${blockHeight}-${Date.now()}`;
        return crypto.createHash('sha256').update(data).digest('hex').substring(0, 16);
    }

    /**
     * Records royalty collection from commercial use
     */
    addRoyalty(amount) {
        if (!this.isActive) {
            throw new Error('This RVT is no longer active');
        }
        this.totalRoyaltiesCollected += amount;
    }

    /**
     * Records royalty distribution to the RVT holder
     */
    distributeRoyalty(amount) {
        if (amount > (this.totalRoyaltiesCollected - this.totalRoyaltiesDistributed)) {
            throw new Error('Cannot distribute more than collected royalties');
        }
        this.totalRoyaltiesDistributed += amount;
    }

    /**
     * Get pending royalties that haven't been distributed yet
     */
    getPendingRoyalties() {
        return this.totalRoyaltiesCollected - this.totalRoyaltiesDistributed;
    }

    deactivate() {
        this.isActive = false;
    }

    toJSON() {
        return {
            rvtId: this.rvtId,
            jobId: this.jobId,
            minedBy: this.minedBy,
            blockHeight: this.blockHeight,
            outputType: this.outputType,
            metadata: this.metadata,
            createdAt: this.createdAt,
            totalRoyaltiesCollected: this.totalRoyaltiesCollected,
            totalRoyaltiesDistributed: this.totalRoyaltiesDistributed,
            pendingRoyalties: this.getPendingRoyalties(),
            isActive: this.isActive
        };
    }
}

module.exports = ResidualValueToken;
